### ISSUE TITLE
Failed to activate the github-web theme

### ISSUE THREAD

**Issue by k0dezz** [JonMidhir/github-web#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.192.0
**System**: linux 3.16.0-34-generic
**Thrown From**: [github-web](https://github.com/JonMidhir/github-web) package, v1.0.0

### Stack Trace

Failed to activate the github-web theme

```
At './stylesheets/base.less' wasn't found in /home/k0dezz/.atom/packages/github-web/index.less:1:0

LessError: './stylesheets/base.less' wasn't found
  at /home/k0dezz/.atom/packages/github-web/index.less:1:0
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "shiny-ui",
      "github-web"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.0
autocomplete-plus, v2.11.0
minimap, v4.7.6
shiny-ui, v0.33.0

# Dev
No dev packages
```

**Comment by JonMidhir** [comment]
Fixed in a8c068eb632acfbc67ae54fe7990c86d2c0e8505.

Please download version 1.1.0.
